/**
 * Client-fulfilled tool names — the single source of truth for which tool
 * names the server must treat as "no execute here; the browser supplies the
 * result via `addToolOutput`".
 *
 * Three namespaces exist today:
 *   - `app_<8hex>` — SEP-1865 app-provided tool aliases, generated by the
 *     client registry (`app-tools-registry.ts`) for tools an MCP app iframe
 *     advertised.
 *   - `ui_*` — MCPJam's own browser-fulfilled tools, hand-named in the
 *     client catalog (`client/src/lib/webmcp/ui-tools-catalog.ts`) and
 *     validated server-side by `validateUiToolEntries`.
 *   - `page_<8hex>` — WebMCP Inspector page tools: tools a real third-party
 *     WEB PAGE registered, which the inspector's browser session invokes over
 *     CDP. Minted per (session, tool) by the inspector store and validated
 *     server-side by `validatePageToolEntries`.
 *
 * WHAT THE `ui_` PREFIX ASSERTS: only that the BROWSER resolves the call.
 * Not that the tool drives a screen — `ui_ask_user` renders a card and waits
 * for an answer — and NOT that it is a WebMCP tool: the catalog is
 * WebMCP-*shaped* but deliberately never exposed to browser-native agents
 * (`document.modelContext` / `navigator.modelContext`). Tools that ARE
 * browser-native WebMCP live under `page_` instead, and the two must not be
 * confused: `ui_` is first-party and curated, `page_` is third-party — and
 * never trusted to describe itself, whatever its annotations claim, though
 * whether a call pauses is the user's Tool Approval switch to decide (see
 * `pageToolCallNeedsApproval`). The prefixes are load bearing because they are this
 * narrow: they are the token the server's skip gate and pause predicate key
 * on, so a browser-fulfilled tool named anything else would either be executed
 * server-side or leave the stream waiting on a result nobody will send.
 *
 * Both the skip gate (`isSkippableClientFulfilledToolCall` in
 * `http-tool-calls.ts`) and the pause predicate
 * (`hasUnresolvedClientFulfilledToolCalls` in `mcpjam-stream-handler.ts`)
 * consume these so the two paths can never drift apart.
 */

import { needsApprovalFor, type ApprovalFloor } from "./tool-approval";

export const APP_TOOL_ALIAS_REGEX = /^app_[a-z0-9]{8}$/i;

/**
 * WebMCP Inspector page-tool aliases, minted per (session, tool) by the
 * inspector store.
 *
 * A third namespace rather than a reuse of `app_`: those are SEP-1865 tools an
 * MCP app iframe advertised, these are tools a THIRD-PARTY WEB PAGE registered
 * and the browser invokes over CDP. Keeping them apart is what lets the
 * approval policy below differ, which it must.
 *
 * Opaque because page-authored names are arbitrary — a model-facing name has to
 * satisfy `^[a-zA-Z0-9_-]{1,64}$`, and a page may register anything at all.
 */
export const PAGE_TOOL_ALIAS_REGEX = /^page_[a-z0-9]{8}$/i;

/**
 * UI tool names are curated, lowercase snake_case with a reserved `ui_`
 * prefix. Max 64 chars total — a strict subset of the Anthropic tool-name
 * charset (`^[a-zA-Z0-9_-]{1,64}$`).
 */
export const UI_TOOL_NAME_REGEX = /^ui_[a-z0-9][a-z0-9_]{0,60}$/;

export function isAppToolAlias(name: string): boolean {
  return APP_TOOL_ALIAS_REGEX.test(name);
}

export function isUiToolName(name: string): boolean {
  return UI_TOOL_NAME_REGEX.test(name);
}

export function isPageToolAlias(name: string): boolean {
  return PAGE_TOOL_ALIAS_REGEX.test(name);
}

/** Floor: the user's switch, like every other tool that acts. */
const PAGE_TOOL_APPROVAL_FLOOR: ApprovalFloor = "setting";

/**
 * Whether a model-requested WebMCP page-tool call must pause for approval.
 *
 * THE USER'S SWITCH, like every other tool that acts.
 *
 * It used to be unconditional, and the reasoning was sound as far as it went: a
 * page tool is code on a third-party site, invoked in a live browser that may
 * be signed into things, and the only signal about what it does is the page's
 * own annotations — claims by the very party whose code would run, which
 * Chromium 151 does not even carry through for imperative registrations (a tool
 * registered `readOnly: true` is reported as `false`; see
 * `webmcp-cdp.spike.test.ts`). None of that changed.
 *
 * What changed is who decides. A person who turns Tool Approval off has said
 * what they want from THIS host, and a family that answers "not you" is a
 * setting that does not work — which is worse for trust than the pill was good
 * for safety, because it teaches people the switch is decorative. The page's
 * annotations are still not evidence and are still never read: the floor is the
 * switch, not the page's word.
 *
 * A person clicking Invoke in the WebMCP tab is a different case entirely and
 * is not gated: they chose the tool, on a page they opened, and the click IS
 * the decision.
 */
export function pageToolCallNeedsApproval(
  requireToolApproval: boolean,
): boolean {
  return needsApprovalFor(PAGE_TOOL_APPROVAL_FLOOR, requireToolApproval);
}

/**
 * True when `name` belongs to a client-fulfilled namespace. Callers that gate
 * on "is this tool call resolved by the browser?" must use this rather than
 * matching one namespace's regex directly.
 */
export function isClientFulfilledToolName(name: string): boolean {
  return isAppToolAlias(name) || isUiToolName(name) || isPageToolAlias(name);
}

/**
 * MCP tool annotations, as defined by the protocol's `ToolAnnotations`.
 *
 * Only the hints MCPJam's first-party `ui_*` catalog sets are modelled. The
 * protocol's defaults are deliberately pessimistic — an absent
 * `destructiveHint` means "assume destructive" — which is what makes an
 * unannotated future tool fail safe rather than execute silently.
 *
 * TRUST BOUNDARY: annotations are hints, and the MCP spec requires clients to
 * treat them as untrusted unless the server is verified. This type — and the
 * approval policy below — apply ONLY to MCPJam's own curated `ui_*` catalog
 * and its server-validated snapshot. Never derive approval policy from a
 * third-party MCP server's annotations.
 */
export interface UiToolAnnotations {
  readOnlyHint?: boolean;
  destructiveHint?: boolean;
  idempotentHint?: boolean;
  openWorldHint?: boolean;
}

/**
 * Whether a UI tool call must pause for the user's approval this turn.
 *
 * Single source of truth for BOTH sides of the approval handshake: the
 * server (per-tool `needsApproval` in `buildUiTools`) and the client (the
 * executor's defer-before-execute gate). They must agree because the client
 * decides "defer" when the tool-call chunk arrives — BEFORE the server's
 * approval-request chunk reaches it. If they disagree, turns strand.
 *
 * The entry's floor decides, and the switch then raises the `setting` rows:
 *   - DESTRUCTIVE actions gate in both modes. The ones a user cannot undo by
 *     looking at the screen are exactly the ones a default-off flag must not
 *     be able to wave through.
 *   - READ-ONLY tools (`ui_snapshot_app`) never gate: they observe, so pausing
 *     buys no safety and costs a click.
 *   - Everything else follows the switch.
 *
 * Entries WITHOUT `annotations` keep the legacy `readOnly`-only semantics —
 * an old client's snapshot must not suddenly start gating differently.
 */
export function uiToolCallNeedsApproval(opts: {
  readOnly: boolean;
  annotations?: UiToolAnnotations;
  requireToolApproval: boolean;
}): boolean {
  return needsApprovalFor(
    uiToolApprovalFloor(opts),
    opts.requireToolApproval === true,
  );
}

/**
 * Which floor one UI catalog entry sits at, read off its annotations.
 *
 * Split out from the predicate so the ANSWER and the SWITCH are separable: the
 * entry's own nature decides the floor, and `requireToolApproval` then decides
 * only the `setting` rows. Same values as the flag-and-annotation ladder this
 * replaces, in the same order.
 */
export function uiToolApprovalFloor(opts: {
  readOnly: boolean;
  annotations?: UiToolAnnotations;
}): ApprovalFloor {
  const { annotations } = opts;
  // Legacy `readOnly`-only entries: an old client's snapshot must not suddenly
  // start gating differently, so a mutating one follows the switch and a
  // read-only one never gates.
  if (!annotations) return opts.readOnly ? "never" : "setting";
  // Destructive wins over everything, including a contradictory
  // `readOnlyHint: true`. The validator rejects `readOnlyHint` disagreeing
  // with `readOnly`, but nothing stops "read-only AND destructive" — and
  // resolving that contradiction in favor of "don't ask" is the one reading
  // that can silently delete something. It decides whether this entry is a
  // READ (never asks) or an ACTION (the switch decides); it no longer
  // overrides the switch, which is the user's to set.
  if (annotations.destructiveHint === true) return "setting";
  // Read-only never gates. Honor BOTH signals: a partial annotation object
  // (e.g. `{destructiveHint: false}`) leaves `readOnlyHint` undefined, and
  // ignoring the legacy flag there would gate a snapshot for no reason.
  if (opts.readOnly || annotations.readOnlyHint === true) return "never";
  // Protocol default: absent destructiveHint means destructive, so an
  // unannotated future tool is treated as an action rather than a read.
  return "setting";
}

/**
 * The catalog id a host attaches to get the browser — the ONE id that maps to
 * the six tool names below (the deliberate 1:N in the built-in catalog).
 *
 * Shared because both sides read it and must not disagree: the server suppresses
 * or builds the toolset from it, and the client decides from the same id whether
 * to offer a Browser pane and list the tools. It lived only on the server, so
 * every client site that needed it wrote the string `"browser"` by hand.
 */
export const BROWSER_BUILT_IN_TOOL_ID = "browser";

/**
 * The six hosted-browser tool names, split by what they DO to the page.
 *
 * Verbs rather than one `browser` mega-tool precisely so this split can
 * exist: an unattended read-only run is built with only the tools that look,
 * and `buildBrowserTools` reads this set to decide which those are.
 */
export const BROWSER_OBSERVATION_TOOL_NAMES: ReadonlySet<string> = new Set([
  "browser_observe",
  /**
   * The LISTING verb, built only where page tools are not first-class.
   *
   * Redundant the moment they are: a whole model step spent asking "does this
   * page have tools?" answers a question the previous step's own result now
   * carries, so `first_class` mode drops it and puts `{count, names}` on every
   * observation instead.
   *
   * It survives here because `MCPJAM_WEBMCP_PAGE_TOOLS=verbs` has to be an
   * exact rollback. Without it that mode advertises `browser_webmcp_invoke` —
   * which takes a tool NAME — and gives the model no way to learn a name or an
   * argument shape.
   */
  "browser_webmcp_tools",
]);

export const BROWSER_INTERACTIVE_TOOL_NAMES: ReadonlySet<string> = new Set([
  "browser_navigate",
  "browser_act",
  "browser_tabs",
  /**
   * Kept ONLY for engines that cannot grow their tool set inside a turn (BYOK,
   * the harness). Where they can, a page's tools are advertised as real
   * `webmcp_*` tools instead — typed, validated and bound to a document
   * generation — and this untyped by-name call is not built at all.
   */
  "browser_webmcp_invoke",
]);

export const BROWSER_TOOL_NAMES: readonly string[] = [
  ...BROWSER_INTERACTIVE_TOOL_NAMES,
  ...BROWSER_OBSERVATION_TOOL_NAMES,
];

export function isBrowserToolName(name: string): boolean {
  return (
    BROWSER_INTERACTIVE_TOOL_NAMES.has(name) ||
    BROWSER_OBSERVATION_TOOL_NAMES.has(name)
  );
}

/**
 * The policy an UNATTENDED run (eval, swarm, journey) declares up front,
 * because nothing can pause to ask it anything.
 *
 * `readOnly` is the only relaxation that reaches the classifier below, and it
 * only ever frees OBSERVATION tools. The origin/tool allowlists are enforced
 * at execute time in `buildBrowserTools`, not here: an allowlist decides
 * WHERE a tool may act, which is a different question from whether a human
 * must confirm it.
 */
export interface BrowserUnattendedPolicy {
  mode: "allow_all" | "read_only" | "allowlist";
  originAllowlist?: readonly string[];
  toolAllowlist?: readonly string[];
}
